// Inside your layout.tsx or as a standard link in your HTML
<link rel="stylesheet" href="/cesium/Widgets/widgets.css" />
// Add this to your layout.tsx
export const viewport = {
  width: 'device-width',
  initialScale: 1,
}
import type { Metadata } from "next";
// 1. Add the import at the top
import { Analytics } from "@vercel/analytics/next";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        {/* This is the correct way to load CSS from the public folder */}
        <link rel="stylesheet" href="/cesium/Widgets/widgets.css" />
      </head>
      <body>{children}
        <Analytics />
      </body>
    </html>
  )
}

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ASIT | Altitude Nexus",
  description: "Generated by Altitude Nexus",
};
